# Generated by Django 4.1.6 on 2023-02-12 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='slug',
        ),
    ]
