# Generated by Django 4.1.6 on 2023-02-12 18:14

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_images_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to=blog.models.user_directory_path),
        ),
    ]
